config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mailer
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: %i[index show edit create destroy update] do
    resources :book_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'

  # DM
  resources :users, only: %i[show edit update]
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show]

  # search post count by calender
  post '/search_by_calender' => 'books#search_by_calender'

  # group
  resources :groups do
    post 'join_group' => 'groups#join_group'
    # event mail
    get '/new_event' => 'groups#notice_event'
    post '/new_event' => 'groups#create_event_mail'
    get '/confirm_mail' => 'groups#confirm_mail'
  end

  # order books
  post 'search_book/order_by_date' => 'books#order_by_date'
  post 'search_book/order_by_rate' => 'books#order_by_rate'

  # search_by_tagname
  post 'search_by_tagname' => 'books#search_by_tag'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true

  has_one_attached :group_image
  def get_group_image(weight, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_fill: [weight, height]).processed
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: %i[edit update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def join_group
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to request.referer
  end

  def destroy
    Group.find(params[:id]).group_users.find_by(user_id: current_user.id).destroy
    redirect_to request.referer
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      @group.users << current_user
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def notice_event; end

  def create_event_mail
    @group_member = Group.find(params[:group_id]).group_users

    @group_member.each do |member|
      EventMailer.with(user_id: member.user.id, title: params[:title],
                       content: params[:content]).notice_email.deliver_later
    end

    render :confirm_mail
  end

  def confirm_mail
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    redirect_to groups_path unless @group.owner_id == current_user.id
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th colspan="3">メンバー</th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td>
          <%= link_to group_path(group.id) do %>
            <%= image_tag group.get_group_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= link_to group_path(group.id) do %>
            <%= group.name %>
          <% end %>
        </td>
        <td><%= group.introduction %></td>
        <td><%= group.group_users.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/confirm_mail.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>送信が完了しました</h1>

      <p>内容は以下の通りです。</p>

      <h2>[タイトル]</h2>
      <p><%= params[:title] %></p>

      <h2>[本文]</h2>
      <p><%= params[:content] %></p>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <h1 class="font-blod">Editing Group</h1>
    <%= form_with model: @group, url: groups_path, method: :post do |f| %>
      <div class="form-group">
        <%= f.label :グループ名 %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :紹介文 %>
        <%= f.text_area :introduction, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :グループ画像 %>
        <%= f.file_field :group_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'groups/index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <h1 class="font-blod">Create Group</h1>
    <%= form_with model: @group, url: groups_path, method: :post do |f| %>
      <div class="form-group">
        <%= f.label :グループ名 %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :紹介文 %>
        <%= f.text_area :introduction, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :グループ画像 %>
        <%= f.file_field :group_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/notice_event.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with url: group_new_event_path(params[:group_id]), method: :post do |f| %>
        <div class="form-group">
          <%= f.label :event_title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :event_content %>
          <%= f.text_area :content, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th colspan="3">メンバー</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image(80,80) %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.group_users.each do |user| %>
                <%= user.user.name %>
                <br />
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>
                <%= link_to 'Notice an Event', group_new_event_path(@group.id), class: "btn btn-sm btn-primary" %>
              <% else %>
                <% if @group.group_users.find_by(user_id: current_user.id).present? %>
                  <%= link_to "left this group", group_path(@group.id), method: :delete, class: "btn btn-sm btn-danger" %>
                <% else %>
                  <%= link_to "join this group", group_join_group_path(@group.id), method: :post, class: "btn btn-sm btn-success" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>