config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mailer
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: %i[index show edit create destroy update] do
    resources :book_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'

  # DM
  resources :users, only: %i[show edit update]
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show]

  # search post count by calender
  post '/search_by_calender' => 'books#search_by_calender'

  # group
  resources :groups do
    post 'join_group' => 'groups#join_group'
    # event mail
    get '/new_event' => 'groups#notice_event'
    post '/new_event' => 'groups#create_event_mail'
    get '/confirm_mail' => 'groups#confirm_mail'
  end

  # order books
  post 'search_book/order_by_date' => 'books#order_by_date'
  post 'search_book/order_by_rate' => 'books#order_by_rate'

  # search_by_tagname
  post 'search_by_tagname' => 'books#search_by_tag'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower # 後ろに付く人を取ってくる(フォロワーを取ってくる、自分がフォローしている人を取ってくる

  has_many :relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :followed # fフォローされる人を取ってくる、フォローしてくれている人を取ってくる

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # DM relation
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # group relation
  has_many :group_users
  has_many :groups, through: :group_users

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def followed_by?(user)
    followings.include?(user)
  end

  def get_profile_image(weight, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [weight, height]).processed
  end

  # guest sign_in method
  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guestuser'
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    def guest_sign_in
      user = User.guest
      sign_in user
      redirect_to user_path(user.id), notice: 'guest userでログインしました'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: %i[edit update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end

    # today's post count
    @todays_post = Book.where(user_id: @user.id, created_at: Time.current.at_beginning_of_day...Time.current).count

    # last day's post count
    @lastdays_post = Book.where(user_id: @user.id,
                                created_at: (Time.current - 1.day).at_beginning_of_day...(Time.current - 1.day).at_end_of_day).count

    # day"s_ratio
    if @todays_post.zero? && @lastdays_post.zero?
      @ratio = 0
    elsif @todays_post.zero?
      @ratio = - (@lastdays_post * 100)
    elsif @lastdays_post.zero?
      @ratio = (@todays_post * 100)
    end

    # this week's post counte
    @week_post = Book.where(user_id: @user.id,
                            created_at: (Time.current - 6.day).at_beginning_of_day...Time.current).count

    # last week's post count
    @lastweek_post = Book.where(user_id: @user.id,
                                created_at: (Time.current - 13.day).at_end_of_day...(Time.current - 7.day)).count

    # week ratio
    if @week_post.zero? && @lastweek_post.zero?
      @week_ratio = 0
    elsif @week_post.zero?
      @week_ratio = - (@lastweek_post * 100)
    elsif @lastweek_post.zero?
      @week_ratio = (@week_post * 100)
    end

    # count the post in a week
    @day_array = [1, 2, 3, 4, 5, 6, 7]

    # define the array to maintain the post count of each day
    @weekposts_array = []

    # find post by loop
    @day_array.each do |i|
      day_num = i - 1
      @weekposts_array.push(Book.where(user_id: @user.id,
                                       created_at: (Time.current - day_num.day).at_beginning_of_day...(Time.current - day_num.day)).count)
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end

  def ensure_guest_user
    user = User.find(params[:id])
    redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。' if @user.name == 'guestuser'
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80,80) %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <td><%= user.name %></td>
  </tr>
  <tr>
	  <th>introduction</th>
	  <td><%= user.introduction %></td>
  </tr>
  <tr>
    <th>follows</th>
    <td><%= link_to user.followings.count, user_followings_path(user) %></td>
  </tr>
  <tr>
    <th>followers</th>
    <td><%= link_to user.followers.count, user_followers_path(user) %></td>
  </tr>
</table>

<div class='row my-3'>
  <div class='w-50'>
    <% if current_user != user %>
      <%= render "relationships/btn", user: user %>
    <% end %>
  </div>
  <% if request.path == "/users/#{user.id}" %>
    <div class="w-50">
      <% unless user.id == current_user.id %>
        <% if (current_user.followed_by? user) && (user.followed_by? current_user)  %>
          <% if @isRoom == true %>
            <div class="user-show-room">
              <%= link_to "チャットを始める", room_path(@room.id), class: "btn btn-primary" %>
            </div>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: user.id %>
              <% end %>
              <div><%= f.submit "チャットを始める", class:"btn btn-primary"%></div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<div class='w-full'>
  <% if user.name != "guestuser" %>
    <div class='row'>
      <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
    </div>
  <% end %>
</div>

app/views/users/_search.html.erb
<%= form_with url: user_search_path, class: "input-group m-4", local:true do |f| %>
  <%= f.text_field :user_search, class: "form-control input-group-prepend", placeholder: "キーワードを入力" %>
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <div class="container px-5 px-sm-0">
          <div id="error_explanation">
            <% if @user.errors.any? %>
              <h3>
                <% if @user.errors.count == 1 %>
                  <%= @user.errors.count %> error prohibited this obj from being saved:
                <% else %>
                  <%= @user.errors.count %> errors prohibited this obj from being saved:
                <% end %>
              </h3>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label><br>
            <%= f.text_field :name, id:"user_name" ,class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label><br>
            <%= f.file_field :profile_image, accept:"image/*" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label><br>
            <%= f.text_area :introduction, id:"user_introduction" ,class: "form-control" %>
          </div>
          <%= f.submit "Update User" ,class: "btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
<%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h2>投稿数の前日比・前週比</h2>
      <%= render 'post_count/dayPostCount', todays_posts: @todays_post, lastdays_post: @lastdays_post, ratio: @ratio %>
      <%= render 'post_count/weekPostCount', week_post: @week_post, lastweek_post: @lastweek_post, week_ratio: @week_ratio %>
      <h2>7日分の投稿数</h2>
      <%= render 'post_count/sevendaysPostCount', day_array: @day_array%>
      <h4 class="text-center text-primary">7日間の投稿数の比較</h4>
      <%= render 'post_count/sevendaysChart', weekposts_array: @weekposts_array, day_array: @day_array %>
      <div class="search_by_calender">
        <%= render 'post_count/searchPostCountByCalender', user: @user %>
      </div>
      <div id="search_res">
        <% if @result.present? %>
          <%= render 'post_count/searchByCalender', result: @result %>
        <% end %>
      </div>
    </div>
  </div>
</div>