config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mailer
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: %i[index show edit create destroy update] do
    resources :book_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'

  # DM
  resources :users, only: %i[show edit update]
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show]

  # search post count by calender
  post '/search_by_calender' => 'books#search_by_calender'

  # group
  resources :groups do
    post 'join_group' => 'groups#join_group'
    # event mail
    get '/new_event' => 'groups#notice_event'
    post '/new_event' => 'groups#create_event_mail'
    get '/confirm_mail' => 'groups#confirm_mail'
  end

  # order books
  post 'search_book/order_by_date' => 'books#order_by_date'
  post 'search_book/order_by_rate' => 'books#order_by_rate'

  # search_by_tagname
  post 'search_by_tagname' => 'books#search_by_tag'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites

  # set the relationship between book and favorites
  has_many :favorited_users, through: :favorites, source: :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  # PV
  is_impressionable counter_cache: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # ratyjs
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  # tag
  acts_as_taggable
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    impressionist(@book, nil, unique: [:ip_address])
  end

  def index
    # set the date of start
    from = (Time.current - 6.day).at_beginning_of_day
    # set the date of end
    to = Time.current.at_end_of_day
    # sort books from the date
    @books = Book.includes(:favorited_users)
                 .sort_by do |x|
      x.favorited_users.includes(:favorites).where(created_at: from...to).size
    end.reverse

    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def search_by_calender
    from = Time.parse(params[:search_date]).at_beginning_of_day
    to = Time.parse(params[:search_date]).at_end_of_day
    @result = Book.where(user_id: params[:user_id], created_at: from...to).count
    render 'post_count/search'
  end

  def order_by_date
    @book = Book.new
    @books = Book.all.order(create_at: :desc)
    render 'index'
  end

  def order_by_rate
    @book = Book.new
    @books = Book.all.order(rate: :desc)
    render 'index'
  end

  def search_by_tag
    tag = ActsAsTaggableOn::Tag.all.find_by(name: params[:tag_name])
    tag_name = tag.present? ? tag.name : nil
    @books = Book.tagged_with(tag_name)
    @book = Book.new
    render 'index'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :tag_list)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user == current_user
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_common.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(63,63) %>
  <table class="table">
    <tbody>
      
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follow</th>
        <th><%= user.followings.count %></th>
      </tr>
      <tr>
        <th>followed</th>
        <th><%= user.followers.count %></th>
      </tr>
      <tr>
        <% if current_user != user %>
          <%= render 'follow/follow', user: user %>
        <% else %>
          <th>
            <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </th>
        <% end %>      
      </tr>
   </tbody>
  </table>
  <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label><br>
        <%= f.text_field :title ,class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label><br>
        <%= f.text_area :body ,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book" ,class: "btn btn-success" %>
      </div>
    <% end %>
</div>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :tag_list, value: book.tag_list.join(','), class: 'form-control' %>
  </div>
  <div class="star form-group">
    <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  var isEdit = $(location).attr('pathname').includes('/edit')

  $('.star.form-group').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'book[rate]',
    half: true,
    readOnly: isEdit,
    score: <%= book.rate %>,
  });
</script>

app/views/books/_good.html.erb
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, class: "heart" do %>
      <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post do %>
      <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  <% end %>
</td>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse table-sm'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
          <% book.tags.each do |tag| %>
            <%= form_with url: search_by_tagname_path, method: :post do |f| %>
              <%= f.hidden_field :tag_name, :value => tag.name %>
              <%= f.submit tag.name, class: "btn btn-link link_primary" %>
            <% end %>
            <br />
          <% end %>
        </td>
        <td class=<%= "favorite-" + book.id.to_s %> >
            <%= render "favorites/btn", book: book %>
        </td>
        <td>
            <div class="book-comments-counter"><%= render "book_comments/counter", book: book %></div>
        </td>
        <td id="star-rate<%= book.id%>">
            <script>
              $('#star-rate<%= book.id%>').raty({
                size      : 36,
                starOff   : '<%= asset_path('star-off.png') %>',
                starOn    : '<%= asset_path('star-on.png') %>',
                starHalf  : '<%= asset_path('star-half.png') %>',
                half      : true,
                readOnly: true,
                score: <%= book.rate %>,
              });
            </script>
          </td>
        <td>
          閲覧数: <%= book.impressions_count%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search.html.erb
<%= form_with url: book_search_path, class: "input-group m-4", local:true do |f| %>
  <%= f.text_field :book_search, class: "form-control input-group-prepend", placeholder: "キーワードを入力" %>
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <div class="container px-5 px-sm-0">
          <div id="error_explanation">
            <% if @book_one.errors.any? %>
              <h3>
                <% if @book_one.errors.count == 1 %>
                  <%= @book_one.errors.count %> error prohibited this obj from being saved:
                <% else %>
                  <%= @book_one.errors.count %> errors prohibited this obj from being saved:
                <% end %>
              </h3>
              <ul>
                <% @book_one.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <%= form_with model: @book_one, method: :patch do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title ,class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body ,class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book" ,class: "btn btn-success"%>
          </div>
        <% end %>
        <%= link_to 'Show', book_path %> | <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新着順", search_book_order_by_date_path, method: :post%> | <%= link_to "評価順", search_book_order_by_rate_path, method: :post %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table table-sm'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td class=<%= "favorite-" + @book.id.to_s %> >
            <%= render "favorites/btn", book: @book %>
          </td>
          <td><div class="book-comments-counter">
            <%= render "book_comments/counter", book: @book %>
            </div>
          </td>
          <td id="star-rate<%= @book.id%>">
            <script>
              $('#star-rate<%= @book.id%>').raty({
                size      : 36,
                starOff   : '<%= asset_path('star-off.png') %>',
                starOn    : '<%= asset_path('star-on.png') %>',
                starHalf  : '<%= asset_path('star-half.png') %>',
                half      : true,
                readOnly: true,
                score: <%= @book.rate %>,
              });
            </script>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %></td>
          <% end %>
        </tr>
      </table>

      <div class="book-comments-index">
        <%= render "book_comments/index", book: @book %>
      </div>

      <div class="comment-textarea">
       <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>