config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # mailer
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: %i[index show edit create destroy update] do
    resources :book_comments, only: %i[create destroy]
    resource :favorites, only: %i[create destroy]
  end

  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'

  # DM
  resources :users, only: %i[show edit update]
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show]

  # search post count by calender
  post '/search_by_calender' => 'books#search_by_calender'

  # group
  resources :groups do
    post 'join_group' => 'groups#join_group'
    # event mail
    get '/new_event' => 'groups#notice_event'
    post '/new_event' => 'groups#create_event_mail'
    get '/confirm_mail' => 'groups#confirm_mail'
  end

  # order books
  post 'search_book/order_by_date' => 'books#order_by_date'
  post 'search_book/order_by_rate' => 'books#order_by_rate'

  # search_by_tagname
  post 'search_by_tagname' => 'books#search_by_tag'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%=  link_to users_path,class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%=  link_to books_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> logout
              <% end %>
            </li>
            <li>
              <%= form_with url: search_by_tagname_path, method: :post do |f| %>
                <%= f.text_field :tag_name, placeholder: "Search" %>
                <%= f.submit "search", class: "btn btn-primary" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path,class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path,class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> login
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", "/", class: "navbar-brand" %>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
               <%= link_to users_path, class: "nav-link text-light" do %>
                 <i class="fas fa-users"></i> Users
               <% end %>
              </li>
              <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete , class: "nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> logout
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path ,class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> login
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>